import { atom } from "jotai";

export const creatureFieldAtom = atom({
  creatureName: "",
  name: "",
  nameMultiple: "",
  nameDescription: "",
  gait: "",
  description: "",
  intelligent: null,
  canSpeak: null,
  canOpenDoors: null,
  canLearn: null,
  benign: null,
  evil: null,
  good: null,
  moods: null,
  trances: null,
  utterances: null,
  trapAvoid: null,
  bonecarn: null,
  carnivore: null,
  eats: true,
  drinks: true,
  fleequick: null,
  lockpicker: null,
  nocturnal: null,
  dinural: null,
  slowLearn: null,
  perfString: "",
  standard: [
    "STANDARD_MATERIALS",
    "STANDARD_TISSUES",
    "VERTEBRATE_TISSUE_LAYERS:SKIN:FAT:MUSCLE:BONE:CARTILAGE",
    "HEAD_HAIR_TISSUE_LAYERS",
  ],
  isStandard: true,
  skin: null,
  scales: null,
  chitan: null,
  standardBody:
    "BODY:HUMANOID_NECK:2EYES:2EARS:NOSE:2LUNGS:HEART:GUTS:ORGANS:HUMANOID_JOINTS:THROAT:NECK:SPINE:BRAIN:SKULL:5FINGERS:5TOES:MOUTH:TONGUE:FACIAL_FEATURES:TEETH:RIBCAGE",
  isStandardBody: true,
});

export const entityFieldAtom = atom({
  entityCode: "",
  controllable: true,
  creature: [],
  translation: "",
  weapons: [],
  ammo: [],
  armor: [],
  helms: [],
  leggings: [],
  gloves: [],
  footware: [],
  traps: [],
  toys: [],
  tools: [],
  clothings: null,
  subterraneanClothing: null,
  currencyByYear: null,
  currency: [],
  symbol: [],
  subselectSymbol: [],
  cullSymbol: [],
  civColor: "",
  religion: "",
  sphere: [],
  ethics: [],
  usesMetal: null,
  usesStone: null,
  woodWeapons: null,
  woodArmor: null,
  usesGem: null,
  indoorWood: null,
  outdoorWood: null,
  gemShape: "",
  stoneShape: "",
  divineCloth: null,
  devineCrafts: null,
  divineWeapons: null,
  divineArmor: null,
  evilAnimals: null,
  goodAnimals: null,
  commonPackAnimals: null,
  commonMounts: null,
  commonPuller: null,
  commonPet: null,
  caveAnimals: null,
  useAnyPets: null,
  useAnimalProducts: null,
  processedWood: null,
  goodPlants: null,
  evilPlants: null,
  evilWood: null,
  indoorFarming: null,
  outdoorFarming: null,
  riverProducts: null,
  oceanProducts: null,
  indoorGardens: null,
  outdoorGardens: null,
  indoorOrchids: null,
  outdoorOrchids: null,
  improveEquipment: null,
  improveBows: null,
  acceptTripute: null,
  entityTeam: "",
  wanderers: [],
  activeSeason: [],
  abuseBodies: [],
  seigeType: "",
  hippy: null,
  construciton: [],
  outdoorConstruction: [],
  banditry: "",
  localBanditry: "",
  diplomatGuards: null,
  niceInvaders: "",
  merchantGuards: null,
  siteType: "",
  likesSite: "",
  toleratesSite: "",
  artStyle: "",
  startBiome: [],
  useableBiome: [],
  merchantNobility: null,
  startingCivs: "",
  maxPupulation: "",
  maxSitePop: "",
  scholars: [],
  miningDisasters: null,
  artForms: [],
  jobs: [],
  reactions: [],
  buildings: [],
  ethics: "",
  values: "",
  abuseBodies: null,
  variableValue: "",
  variablePositions: null,
  siteVariablePostions: null,
  gemTypes: "",
  nobles: "",
  popsControllable: null,
});

export const metalFieldAtom = atom({
  codeName: "",
  name: "",
  displayColor: "",
  buildColor: "",
  magmaSafe: true,
  uses: [],
  density: "",
  molarMass: "",
  impactYield: "",
  impactFracture: "",
  impactStrainAtYield: "",
  compressiveYield: "",
  compressiveFracture: "",
  compressiveStrainAtYeild: "",
  torsionYield: "",
  torsionFracture: "",
  torsionStrainAtYield: "",
  shearYield: "",
  shearFracture: "",
  shearStrainAtYield: "",
  bendingYield: "",
  bendingFracture: "",
  bendingStrainAtYield: "",
  maxEdge: "",
  stateColor: "",
});

export const weaponFieldAtom = atom({
  itemCode: "",
  name: "",
  namePlural: "",
  size: "",
  skill: "",
  twoHanded: "",
  minSize: "",
  matSize: "",
  attacks: [],
  ranged: false,
  rangedAmmoClass: "",
  rangedskill: "",
  shootForce: "",
  ammoCode: "",
  ammoName: "",
  ammoNamePlural: "",
  ammoClass: "",
  ammoSize: "",
  ammoAttacks: [],
});
